### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by bnharvey** [stefanbode/Sonoff-Tasmota#7]
Hi,
     Tried to compile with Arduino IDE 1.8.3 and i'm getting this error. pcf8574 libarary seems to be installed. Any ideas would be appreciated @stefanbode 
Thanks

C:\Users\Brad Harvey\Downloads\Sonoff-Tasmota-stefan_patch1\Sonoff-Tasmota-stefan_patch1\sonoff\sonoff.ino: In function 'void setRelay(uint64_t)':

sonoff:353: error: 'pcf8574_switchrelay' was not declared in this scope

       pcf8574_switchrelay(i, state);

                                   ^

C:\Users\Brad Harvey\Downloads\Sonoff-Tasmota-stefan_patch1\Sonoff-Tasmota-stefan_patch1\sonoff\sonoff.ino: In function 'void every_second()':

sonoff:1652: error: 'pcf8574_detect' was not declared in this scope

         pcf8574_detect();

                        ^

C:\Users\Brad Harvey\Downloads\Sonoff-Tasmota-stefan_patch1\Sonoff-Tasmota-stefan_patch1\sonoff\sonoff.ino: In function 'void GPIO_init()':

sonoff:2103: error: 'pcf8574_Init' was not declared in this scope

     pcf8574_Init();

                  ^

C:\Users\Brad Harvey\Downloads\Sonoff-Tasmota-stefan_patch1\Sonoff-Tasmota-stefan_patch1\sonoff\webserver.ino: In function 'void startWebserver(int, IPAddress)':

webserver:329: error: 'handleI2C' was not declared in this scope

       webServer->on("/i2c", handleI2C);

                             ^

C:\Users\Brad Harvey\Downloads\Sonoff-Tasmota-stefan_patch1\Sonoff-Tasmota-stefan_patch1\sonoff\webserver.ino: In function 'void handleSave()':

webserver:929: error: 'pcf8574_saveSettings' was not declared in this scope

       pcf8574_saveSettings();

                            ^

exit status 1

**Comment by stefanbode** [comment]
Please use the master Branch
